name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run containers
        run: >
          ROUTER_NAME=wedding_app
          DOMAIN=josepha-und-felix.de
          IMAGE_TAG=latest
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOSTNAME=yzYTXR
          /usr/local/bin/docker-compose --file docker-compose.yml --project-name wedding_app up --detach --remove-orphans --build